openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: https://29abb700-c779-4e23-b304-81fce79e18df-dev.e1-us-east-azure.choreoapis.dev/default/fiance-endpoint/v1.0
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /add-record:
    post:
      summary: adds a record in firebase.
      description: same
      responses:
        "200": # status code
          description: Record added Successfully!
          content:
            application/json:
              schema:
                type: json
                items:
                  type: string
        "500":
          description: Some error occured.
  /records:
    get:
      summary: Returns a list of records.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        user : string
      responses:
        "200": # status code
          description: A JSON array records
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    body: string
                    readable-date: string
                    address : string
  /wake-up:
    get:
      summary: Returns a status.
      description: Returns the status.
      responses:
        "200": # status code
          description: Successfully woke up.
        "500" : status code
          description : Error
